# Generated by Django 3.2.13 on 2022-06-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomname', models.CharField(help_text="Enter room's name", max_length=20, unique=True)),
                ('minutes', models.IntegerField()),
                ('seconds', models.IntegerField()),
                ('pause', models.BooleanField(default=True)),
                ('message', models.TextField(help_text="Chat room's messages")),
            ],
            options={
                'ordering': ['roomname'],
            },
        ),
    ]
